### ISSUE TITLE
npm, bower package

### ISSUE THREAD

**Issue by PanJ** [omise/omise.js#4]
Hello Omise team,

Thank you you guys for creating such an awesome payment API. I want to request npm and/or bower submission for this wonderful library.

**Comment by fred** [comment]
Hi @PanJ Thanks for the support and compliments! 
Omise.js is only a Javascript library hosted on the CDN, and it's only supposed to run on the client browser. We may have to change it sometimes and update the file on the CDN. 
For this reason I believe an NPM Package would not be necessary.
Our Node.js library already has NPM package https://github.com/omise/omise-node
Thanks for your interesting in wishing to contribute to Omise.
If other projects or our Omise-Node.js interests you, please contact us.
Regards.

**Comment by PanJ** [comment]
Thank you for your fast reply.

About the bower package, other than dependency management, I think that bower is good in sense of versioning. You can change the api without worrying that your new file on CDN will not compatible to older users.

And for npm, I am currently developing somewhat "isomorphic" web, so I prefer npm over bower in order to share my code in both server and client.

**Comment by sirn** [comment]
Hi @PanJ,

The Omise.js is strictly an interface to the Vault API which is supposed to be called from the client, as opposed to the other APIs which are to be called from the server.

While it may possible to put Omise.js in NPM or Bower, I think this is one of the case where including it in package manager gives very little benefit (also does include it as part of website's assets bundle) since we need to keep the API and Omise.js strictly in sync. Relying on package manager will pretty much force the user to redeploy every time we make any changes to the Vault. This is even more true with #3 when we switched use EasyXDM and Vault Provider.

Another problem of including in NPM may be that it may cause confusion with the node package, which is named [omise](https://www.npmjs.com/package/omise). The node-omise also provides a wrapper for [Token API](https://docs.omise.co/api/tokens/) which is similar to what Omise.js provides (although primary objective of the Token API was for testing, as your server should never receive the card number).

We'll see of what we can do though, but as stated above, I see very little benefit of doing so.

**Comment by robinclart** [comment]
@PanJ I noticed you talked about writing isomorphic code. You need to apply extreme caution with that. The `omise-node` library is solely made to be used server-side. The main reason being that *you should never share your secret key*. The only key you can use on your frontend is your public key which is used solely for creating tokens. Tokens are useless in themselves. But combined with your secret key it is possible to charge the card linked to those tokens.

If you ever noticed that you pushed your key on your frontend you can easily roll your secret key on the [dashboard](http://dashboard.omise.co/test/api-keys).

**Comment by PanJ** [comment]
Hello, @sirn 
Your answer is quite clear for me. I have a suggestion for omise.js that it should not depend on jQuery. I assume that jQuery is used for the xhr to communicate with your Vault API. I think that this can be implemented in a self-dependent manner.

@robinclart Thank you for your advice. I am aware of the caution. The charging procedure is implemented separately on our REST API.

Since Google Maps API also requires me to include the library separately, I am OK with the current approach. Thank you everyone for joining the discussion. I am closing the issue.

**Comment by PanJ** [comment]
Hi all,

I want to reopen the issue because I found another use case. When I want to create tests for our booking process (using Mocha). I cannot obtain token from Omise vault because I cannot run Omise.JS using NodeJS. Do you have any suggestion on any workaround?

**Comment by sirn** [comment]
Hi, @PanJ 

Is it possible to use `omise.tokens.create` in [omise-node](https://docs.omise.co/api/tokens/) in that case? Please note that creating token server-side should not be used in production unless you have PCI, but it should be OK for test cards in test mode.
