### ISSUE TITLE
Issue with single page application

### ISSUE THREAD

**Issue by ascentsentrepreneurs** [omise/omise.js#78]
Hello Omise.js team,
I'm integrating Omise.js into my Odoo PoS (Single page Application), So by using this Omise.js My page is getting reloaded due to form submission, I want to get the data(reponse) in Javascript promise or something, without reloading the page.

Can someone please help me with this?

Many thanks.

**Comment by davidsneighbour** [comment]
Hi @ascentsentrepreneurs, I had the same experience in the beginning, due to a faulty implementation. The form-submit event needs to receive a `return false` so the form is not actually sent, then the omise-js is retrieving the token and on return of the data the form is sent by `form.submit()`. If you can offer a public repo with a sample app for your case it might be easy to help out.

**Comment by ascentsentrepreneurs** [comment]
Hello @davidsneighbour  thanks for the reply. I'll try to make a public repo, demonstrating my app and post it here.
Thanks.

**Comment by ascentsentrepreneurs** [comment]
@davidsneighbour  I want to use  the Omise's  [Pre-built Payment Form](https://www.omise.co/omise-js#pre-built-payment-form)
 [Using-Javascript](https://www.omise.co/omise-js#using-javascript) it should not reload the page when we receive the token response.

**Comment by ascentsentrepreneurs** [comment]
Okay @davidsneighbour  you were right. I was implementing it in wrong way. I've implemented solution based on your guidance. now it's working. Thanks for the help.
Now you can close the issue.

**Comment by danfowler** [comment]
Thanks @davidsneighbour @ascentsentrepreneurs!  Closing now, but will try to use this example to inform future guidance 👍
